### ISSUE TITLE
"öffnen" statt "intro"

### ISSUE THREAD

**Issue by lmehrwa1** [thomas-institut/summa#6]
![image](https://user-images.githubusercontent.com/115229914/214327640-bc0c67b5-6428-400e-8dbb-411bacfa271f.png)
_intro_ ist bloß eine technische, interne Bezeichnung für die namenlosen (Ab-)Sätze, die zwischen Titel der Quaestio und jeweils erstem Articulus stehen.
Jedwede Neuerfindung wird Verwirrung stiften. Statt einer Bezeichnung könnte man einfach _öffnen_ oder _jump to_ anzeigen.

**Comment by lmehrwa1** [comment]
Es muss aber auf jeden Fall irgendetwas angezeigt werden, weil hier der Link hinterlegt ist. Ansonsten ließen sich die Prologe nicht öffnen, weil dort "intro" der einzige Unterpunkt ist und es keine Articuli gibt.

**Comment by ashtree4711** [comment]
Mhh. Mal in der größeren Runde besprechen?
